"""add_enterprise_platform_tables

Revision ID: 15f8fe3f7945
Revises: 5b3fd21628d8
Create Date: 2026-09-09 11:46:31.807218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f8fe3f7945'
down_revision: Union[str, Sequence[str], None] = '5b3fd21628d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
